### ISSUE TITLE
Running 1 learner 2 actors on single gpu machine

### ISSUE THREAD

**Issue by jodusan** [jaimeyzzz/impala_horovod_gym#1]
When running single learner setup one of the actors will eat all gpu memory should the [line](https://github.com/loyave/impala_horovod_gym/blob/dev-horovod/experiment.py#L364) be placed before is_learner check?

**Comment by pengsun** [comment]
Hi @dulex123 , thanks for the question!
Did you run it with `run_experiment_mm_raw.py` or with the native distributed TF?

For the former, this line
https://github.com/loyave/impala_horovod_gym/blob/9b6d7a2af7da6f511926d6f789b41e284cd1ba7b/run_experiment_mm_raw.py#L179
ensures actor wont use GPU

For the latter, yes, current examples are incorrect, we should add `CUDA_VISBLE_DEVICES= ` before each `experiment.py` call as actor.
Will update the doc later.

**Comment by jodusan** [comment]
Cool, thanks!
