### ISSUE TITLE
Network bandwidth for actor update limit

### ISSUE THREAD

**Issue by jodusan** [jaimeyzzz/impala_horovod_gym#2]
Is there a rough/precise calculation of computer network bandwidth limit before it becomes a bottleneck? For example how many actors can one learner support before computer network bottlenecks? (i.e. 70mb neural network weights)

Is there any machine level caching involved if multiple actors are on the same machine? (no reason for all of them to pull same weights at the same time)

**Comment by jodusan** [comment]
Hey guys, any info on this?

**Comment by pengsun** [comment]
Hi @dulex123, a calculation of the required bandwidth is hard, as the time cost involves many factors, see the discussion in the original `scalable_agent` code here:
https://github.com/deepmind/scalable_agent/issues/14

But we can identify how many actors (each a CPU machine deployed remotely) are "saturated" for a single learner experimentally. According to my previsous test over PongNoFrameskip-v4 (wrapped as is in `atari_env.py`), when adopting the ResNet-LSTM net described in the paper with bath_size=32, unroll_length=100, the maximum number of actors that a learner can "carry" is around 60, when the training throughput  is around 6K (or x4 = 24K env frames by counting the skip-frame=4).  Adding more actors than 60 would not further increase the throughput.

Will update the numbers and tables in the README later.

**Comment by jodusan** [comment]
Thanks! That is very helpful.

And what about the actors that reside on the same machine? Could they benefit from a weights caching mechanism? So that the learner does not send weight to each actor separately but to each machine. That may reduce network traffic considerably

**Comment by pengsun** [comment]
Hi @dulex123, I am actually not sure of that...

On the one hand, the code relies on distributed tensorflow to communicate between actor-learner. I guess the distributed tensorflow (relying on gRPC) could detect whether the two processes reside on the same machine and implement a fast sending/receiving if they do.

On the other hand, when using hundreds of actors, I guess the benefit of doing so is negligible.

**Comment by pengsun** [comment]
The corresponding note has been added here:
https://github.com/loyave/impala_horovod_gym/blob/dev-horovod/sandbox/speed.md

**Comment by jodusan** [comment]
@pengsun Yes but if you use 120 actors in total on three machines (40 actors per machine) and a single machine with a gpu for learner, than you can gain considerable throughput. 

Thank you for the performance table! 

Also would you mind sharing what cloud platform you use to scale training? 

Cheers

**Comment by pengsun** [comment]
Hi @dulex123, unfortunately it's a private service in our company... 

But basically the rationale and the settings should be the same for any other public available cloud like EC2/Azure/Google.

**Comment by jodusan** [comment]
Thanks !
