### ISSUE TITLE
Distributed FPS measurement

### ISSUE THREAD

**Issue by jodusan** [jaimeyzzz/impala_horovod_gym#3]
Hello again! 

How did you get measurements in [this table](https://github.com/loyave/impala_horovod_gym/blob/dev-horovod/sandbox/speed.md). Did you just use num_environment_frames thats printed in the console? 

If yes, is that number representative of multiple learners or just the single one thats printing it? 

Thanks!

**Comment by pengsun** [comment]
Hi, it can be read from the console output, but a more convenient way is to read it  from Tensorboard. In both cases, it is under the name `num_environment_frames`.  Note in our modified code we've excluded the repeated_frames, so your should times, e.g., 4 to make it comparable to the speed in raw env frames as reported in the original impala paper.

Each number in [this table](https://github.com/loyave/impala_horovod_gym/blob/dev-horovod/sandbox/speed.md) is for all the learners. From the Tensorboard you are able to read the number for a single learner, and you should time it by number-of-learners manually. It involves the mechanism of Horovod, see the discussion here: https://github.com/uber/horovod/issues/461
